repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]
  - repo: local
    hooks:
      - id: cz-changelog
        name: Commitizen Changelog
        entry: bash -c "cz changelog && git add CHANGELOG.md && git commit --amend --no-edit"
        language: system
        stages: [ commit ]